eureka:
  instance:
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    home-page-url-path: /
    hostname: localhost
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
server:
  port: 8500
spring:
  security:
    user:
      name: admin
      password: will.chen
  application:
    name: eureka-server
info:
  name: '@project.artifactId@'
  description: '@project.description@'
  version: '@project.version@'
  spring-boot-version: '@spring.boot.version@'
  spring-cloud-version: '@spring-cloud.version@'